### ISSUE TITLE
Make It Testable

### ISSUE THREAD

**Issue by edgrosvenor** [edgrosvenor/tupleauth#1]
Orchestra testbench doesn't come with the auth scaffolding installed and my half assed attempts at getting it in place failed.

**Comment by jamessessford** [comment]
Fixed the testing issue and made a pull request. I'll look at adding more of the test over the next couple of days if I have the chance

**Comment by jamessessford** [comment]
Hey again fella - I've added some more stuff to https://github.com/edgrosvenor/tupleauth/pull/3 - hopefully it fits what you needed!
